### PR TITLE
Login Page and Create Account Page

### PR DESCRIPTION
**Pull request by amritha-patil**
Adding the first 2 pages.

### CODE REVIEW

**Review by Srikanth-Kandarp — CHANGES_REQUESTED** [review]
Can you add the screen shots everytime you make a PR

**Comment by Srikanth-Kandarp** [comment]
Hey, Update the PR By Tomorrow Noon

**Comment by amritha-patil** [comment]
Added Media Query and solved the continue button issue.

**Comment by Srikanth-Kandarp** [comment]
# Overall Couple of Points to get it right !!

## 1. All your widgets are not matched up 
Screenshot 2021-04-13 at 9 03 44 PM

## 2. Now you have chosen an android UI so we also include material icons for IOS have a look at it 
https://flutter.dev/docs/development/ui/widgets/cupertino

- Sample 1 
Screenshot 2021-04-13 at 9 04 23 PM

- Sample 2
Screenshot 2021-04-13 at 9 22 42 PM


These are not part of the IOS UI so you have to make the widgets dynamic as well 

## 3. UNIFORMITY is the key I don't see the uniformity actually so please go through it 

- Look at this as the text box 

Screenshot 2021-04-13 at 9 23 13 PM

and here it's not the same 

Screenshot 2021-04-13 at 9 22 33 PM

## 4. Fonts --> I thought I mentioned it if not sorry about it.. it's called **Product Sans** 
https://befonts.com/product-sans-font.html

## 5. File Structure isn't good at all tbh name the files in a proper way like page 1 of something 
Screenshot 2021-04-13 at 9 18 11 PM

-------------
Also sorry if I was harsh while reviewing your code also here's how Grammarly says it lol how my comment was on your code 

Screenshot 2021-04-13 at 9 26 24 PM

**Review by Apoorva10100 — COMMENTED** [review]
1. The suffix icon and cursor on most your password text fields are blue. Look into that
2. Keep your assets and fonts (which i have added, use that, it will be common) out of the utils folder. Keep only dart files in the lib folder.
3. Alignment of the registeration page is off. There is too much padding on the outer side.
4. The focus of the text fields are off. I need to click on each text field before entering values. Make it such that when i press the enter button, i automatically go to the next field.
5. Use the CupertinoDatePicker class for the calendar.
6. Store your values in variables and make sure the functionalities work. Go to an empty page on login or registeration to make sure they work. It will be easier when you have to integrate it with backend.

**Comment by Srikanth-Kandarp** [comment]
Hey Patil for some reason when i do flutter release I get everything as empty do check it out and update it by tomorrow if possible 

Here are the Sceenshots 

IMG_0427
IMG_0426
IMG_0425


also a thing : before you push anything do check it out with this commad
```
flutter run --release
```

**Review by Srikanth-Kandarp — APPROVED** [review]

**Pull request merged**
