### PR TITLE
News Feed Page

### PR DESCRIPTION
**Pull request by dhiraj2803**

### CODE REVIEW

**Comment by Srikanth-Kandarp** [comment]
Update the PR By Tomorrow Noon

**Review by Srikanth-Kandarp — CHANGES_REQUESTED** [review]
.

**Comment by Srikanth-Kandarp** [comment]
# Update these changes 

## 1. Comments .. bro you didn't add any comments to the code you should actually comment everything like if you are using a container then comment like for what you are using this widget that as well so that when we are passing on to sir that they know what is there and what is no 
PS: Look at Amritha's Code she is commented very well 

## 2. Fonts... So I think I put it on the group that we are using **Product Sans** for fonts ... please look at it 
https://befonts.com/product-sans-font.html

## 3. So you have hard-coded everything according to your emulator so when I run it on a different size phone what happens Is that it cuts out ... so you have to use a widget called "Media Query" 

* How it looks on different Phone 
Screenshot 2021-04-16 at 12 41 48 PM

## 4. Now the big thing is that the Good Afternoon Text that you had on the above screen is supposed to be inside the scaffold, not the app bar .. we don't have an App Bar in our design it's supposed to say Good Afternoon/Morning/Evening User but that User Name you will get it from an API when connecting so Fix that 

## 5. Cards Look Okay but we have to have a "Like Count' inside the card preview as well 

## 6. Navigation Bar Looks Great but the Alignment isn't proper and Use the Texts as they are in the Figma File 

* The Allignement issue look at Profile it is supposed to be centered 
Screenshot 2021-04-16 at 12 47 29 PM

* This is not Notification actually its Complaints but that is for release 2 but change the text 
Screenshot 2021-04-16 at 12 48 07 PM

* Make it Unifrom "Home Feed" okay.. so instead of Home Feed make it "News Feed"
Screenshot 2021-04-16 at 12 49 31 PM

## 7. Okay so we don't have any share button there in the design so have a look at the design i will update it now and make it the same way 
Screenshot 2021-04-16 at 12 49 55 PM

------------------

Yeah bro that's it make all the changes and update it by tomorrow its already late.

**Comment by Apoorva10100** [comment]
So, couple of things
1.  The selected page in the taskbar
image
can you make it grey like in the design?

2. Try giving more padding on top, to the "good morning/ evening" text? it is too close to the top .

3. Increase the width of the cards and give a little more distance between the cards.

4. Make the content in the card in the main page normal and not bold.
image
"big hole" part seems fine. but the contents, doesnt look good.

5. remove the three dots icon from the card and from the feed page.

6. remove the "TITLE----" line when youre sharing the card
image

7. add borders to the cards like the design

make these changes asap

**Comment by Apoorva10100** [comment]
1. Make the video wider
2. Remove the "Title" word in the sharing part
3. And the page moves when you click on the share button
image

**Review by Srikanth-Kandarp — APPROVED** [review]

**Pull request merged**
